const products={
 heat:{name:'Heat Reactive Tee',price:949,old:1499,type:'heat',desc:'Body heat se color change hone wala unique tee. Touch karo aur magic dekho.'},
 water:{name:'Water Reveal Tee',price:899,old:1299,type:'water',desc:'Pani dalte hi hidden design reveal hota hai. Reels ke liye perfect.'},
 sun:{name:'Sunlight Activated Tee',price:999,old:1599,type:'sun',desc:'Dhoop me aate hi color active. Outdoor aur college look ke liye best.'},
 gym:{name:'Gym Performance Tee',price:1299,old:1799,type:'gym',desc:'Jitna zyada workout, utna zyada color change. Sweat aur body heat reactive gym tee.'},
 hoodie:{name:'Color Changing Hoodie',price:2499,old:3499,type:'water',desc:'Premium hoodie with reactive print and streetwear look.'},
 kids:{name:'Kids Magic Tee',price:699,old:999,type:'sun',desc:'Kids ke liye magic reveal t-shirt.'},
 couple:{name:'Couple Reveal Tee',price:1799,old:2499,type:'heat',desc:'Couple message reveal design, gifting ke liye best.'}
};
function productCard(key,p=products[key]){return `<a class="prod" href="product.html?id=${key}"><div class="prod-img"><span class="badge">${key==='gym'?'NEW':'SALE'}</span><div class="tee ${p.type}"></div></div><h3>${p.name}</h3><div class="stars">★★★★★ <small>(${key==='gym'?986:248})</small></div><div><span class="price">₹${p.price}</span><span class="cut">₹${p.old}</span></div></a>`}
function renderProducts(){document.querySelectorAll('[data-products]').forEach(el=>{el.innerHTML=Object.keys(products).map(k=>productCard(k)).join('')})}
function setupDetail(){const box=document.querySelector('[data-product-detail]');if(!box)return;const id=new URLSearchParams(location.search).get('id')||'gym';const p=products[id]||products.gym;document.title=p.name+' - ColorFlip Wear';box.innerHTML=`<div class="gallery"><div class="main-img"><div class="tee ${p.type}"></div></div><div class="thumbs"><div class="thumb"><div class="tee ${p.type}"></div></div><div class="thumb"><div class="tee heat"></div></div><div class="thumb"><div class="tee water"></div></div><div class="thumb"><div class="tee sun"></div></div></div></div><div class="detail-info"><div class="crumb">Home / Shop / ${p.name}</div><h1>${p.name} <span class="tag">${id==='gym'?'NEW':'TRENDING'}</span></h1><div class="stars">★★★★★ <small>(986 reviews)</small></div><h2>₹${p.price} <span class="cut">₹${p.old}</span></h2><p>${p.desc}</p><div class="notice">${id==='gym'?'More exercise = more heat = more color change. Aapki mehnat tee par dikhegi.':'Color-changing effect lighting, heat ya water condition ke hisab se activate hota hai.'}</div><h3>Select Size</h3><div class="size-row"><span class="size">S</span><span class="size active">M</span><span class="size">L</span><span class="size">XL</span><span class="size">XXL</span></div><br><a class="btn dark" href="cart.html">ADD TO CART</a> <a class="btn primary" href="checkout.html">BUY NOW</a><br><br><div class="info white"><b>Features</b><p>Skin-safe inks • Premium fabric • Machine washable • Fast delivery</p></div></div>`}
function cartCount(){document.querySelectorAll('[data-cart]').forEach(e=>e.textContent='🛒 3')}
document.addEventListener('DOMContentLoaded',()=>{renderProducts();setupDetail();cartCount();});
